language: python
python:
    - "2.7"
    - "3.5"
sudo: true

before_install:
  - git config --global user.email "OpenStack_TravisCI@f5.com"
  - git config --global user.name "Travis F5 Openstack"
install:
  - pip install tox
  - pip install -r requirements.unittest.txt
  - pip install -r requirements.style.txt
  - python ./setup.py install
script:
  - tox -e style
  - tox -e unit
  # TEST DOCS
  - make docker-test
deploy:
  # deploy docs to s3
  # if this is NOT a tagged release, the docs go to /products/openstack/ml2-driver/$TRAVIS_BRANCH
  - provider: script
    skip_cleanup: true
    on:
      repo: F5Networks/f5-openstack-ml2-driver
      branch: master
      condition: $TRAVIS_TAG = ""
    script:
    - make deploy-branch
  # if this is a tagged release, the docs go to /products/openstack/ml2-driver/$TRAVIS_BRANCH/vX.Y
  - provider: script
    skip_cleanup: true
    on:
      tags: true
      repo: F5Networks/f5-openstack-ml2-driver
    script:
    - make deploy-release
